//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  homepage: Homepage;
  homepageConnection: HomepageConnection;
  capabilities: Capabilities;
  capabilitiesConnection: CapabilitiesConnection;
  caseStudy: CaseStudy;
  caseStudyConnection: CaseStudyConnection;
  blogPost: BlogPost;
  blogPostConnection: BlogPostConnection;
  testimonials: Testimonials;
  testimonialsConnection: TestimonialsConnection;
  siteSettings: SiteSettings;
  siteSettingsConnection: SiteSettingsConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomepageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomepageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomepageFilter>;
};


export type QueryCapabilitiesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryCapabilitiesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CapabilitiesFilter>;
};


export type QueryCaseStudyArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryCaseStudyConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CaseStudyFilter>;
};


export type QueryBlogPostArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBlogPostConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BlogPostFilter>;
};


export type QueryTestimonialsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTestimonialsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TestimonialsFilter>;
};


export type QuerySiteSettingsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteSettingsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteSettingsFilter>;
};

export type DocumentFilter = {
  homepage?: InputMaybe<HomepageFilter>;
  capabilities?: InputMaybe<CapabilitiesFilter>;
  caseStudy?: InputMaybe<CaseStudyFilter>;
  blogPost?: InputMaybe<BlogPostFilter>;
  testimonials?: InputMaybe<TestimonialsFilter>;
  siteSettings?: InputMaybe<SiteSettingsFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Homepage | Capabilities | CaseStudy | BlogPost | Testimonials | SiteSettings | Folder;

export type HomepageCompanies = {
  __typename?: 'HomepageCompanies';
  name: Scalars['String']['output'];
  logo?: Maybe<Scalars['String']['output']>;
};

export type HomepageSeo = {
  __typename?: 'HomepageSeo';
  metaTitle?: Maybe<Scalars['String']['output']>;
  metaDescription?: Maybe<Scalars['String']['output']>;
  ogImage?: Maybe<Scalars['String']['output']>;
};

export type Homepage = Node & Document & {
  __typename?: 'Homepage';
  headline: Scalars['String']['output'];
  subtitle: Scalars['String']['output'];
  photo?: Maybe<Scalars['String']['output']>;
  shippedResultsLabel?: Maybe<Scalars['String']['output']>;
  companies?: Maybe<Array<Maybe<HomepageCompanies>>>;
  aboutHeading?: Maybe<Scalars['String']['output']>;
  aboutText?: Maybe<Scalars['String']['output']>;
  seo?: Maybe<HomepageSeo>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HomepageCompaniesFilter = {
  name?: InputMaybe<StringFilter>;
  logo?: InputMaybe<ImageFilter>;
};

export type HomepageSeoFilter = {
  metaTitle?: InputMaybe<StringFilter>;
  metaDescription?: InputMaybe<StringFilter>;
  ogImage?: InputMaybe<ImageFilter>;
};

export type HomepageFilter = {
  headline?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  photo?: InputMaybe<ImageFilter>;
  shippedResultsLabel?: InputMaybe<StringFilter>;
  companies?: InputMaybe<HomepageCompaniesFilter>;
  aboutHeading?: InputMaybe<StringFilter>;
  aboutText?: InputMaybe<StringFilter>;
  seo?: InputMaybe<HomepageSeoFilter>;
};

export type HomepageConnectionEdges = {
  __typename?: 'HomepageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Homepage>;
};

export type HomepageConnection = Connection & {
  __typename?: 'HomepageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomepageConnectionEdges>>>;
};

export type CapabilitiesTabsMetrics = {
  __typename?: 'CapabilitiesTabsMetrics';
  highlight: Scalars['String']['output'];
  description: Scalars['String']['output'];
  detail?: Maybe<Scalars['String']['output']>;
  image1?: Maybe<Scalars['String']['output']>;
  image2?: Maybe<Scalars['String']['output']>;
  image3?: Maybe<Scalars['String']['output']>;
  url?: Maybe<Scalars['String']['output']>;
  ctaText?: Maybe<Scalars['String']['output']>;
  ctaUrl?: Maybe<Scalars['String']['output']>;
};

export type CapabilitiesTabs = {
  __typename?: 'CapabilitiesTabs';
  id: Scalars['String']['output'];
  label: Scalars['String']['output'];
  accent: Scalars['String']['output'];
  metrics?: Maybe<Array<Maybe<CapabilitiesTabsMetrics>>>;
};

export type Capabilities = Node & Document & {
  __typename?: 'Capabilities';
  tabs?: Maybe<Array<Maybe<CapabilitiesTabs>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type CapabilitiesTabsMetricsFilter = {
  highlight?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  detail?: InputMaybe<StringFilter>;
  image1?: InputMaybe<ImageFilter>;
  image2?: InputMaybe<ImageFilter>;
  image3?: InputMaybe<ImageFilter>;
  url?: InputMaybe<StringFilter>;
  ctaText?: InputMaybe<StringFilter>;
  ctaUrl?: InputMaybe<StringFilter>;
};

export type CapabilitiesTabsFilter = {
  id?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
  accent?: InputMaybe<StringFilter>;
  metrics?: InputMaybe<CapabilitiesTabsMetricsFilter>;
};

export type CapabilitiesFilter = {
  tabs?: InputMaybe<CapabilitiesTabsFilter>;
};

export type CapabilitiesConnectionEdges = {
  __typename?: 'CapabilitiesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Capabilities>;
};

export type CapabilitiesConnection = Connection & {
  __typename?: 'CapabilitiesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<CapabilitiesConnectionEdges>>>;
};

export type CaseStudySeo = {
  __typename?: 'CaseStudySeo';
  metaTitle?: Maybe<Scalars['String']['output']>;
  metaDescription?: Maybe<Scalars['String']['output']>;
  ogImage?: Maybe<Scalars['String']['output']>;
};

export type CaseStudy = Node & Document & {
  __typename?: 'CaseStudy';
  title: Scalars['String']['output'];
  company?: Maybe<Scalars['String']['output']>;
  coverImage?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  publishedDate?: Maybe<Scalars['String']['output']>;
  seo?: Maybe<CaseStudySeo>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type CaseStudySeoFilter = {
  metaTitle?: InputMaybe<StringFilter>;
  metaDescription?: InputMaybe<StringFilter>;
  ogImage?: InputMaybe<ImageFilter>;
};

export type CaseStudyBodyCalloutFilter = {
  type?: InputMaybe<StringFilter>;
  heading?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
};

export type CaseStudyBodyCtaBannerFilter = {
  heading?: InputMaybe<StringFilter>;
  buttonText?: InputMaybe<StringFilter>;
  buttonUrl?: InputMaybe<StringFilter>;
};

export type CaseStudyBodyCaptionedImageFilter = {
  image?: InputMaybe<ImageFilter>;
  caption?: InputMaybe<StringFilter>;
  attribution?: InputMaybe<StringFilter>;
};

export type CaseStudyBodyFilter = {
  Callout?: InputMaybe<CaseStudyBodyCalloutFilter>;
  CTABanner?: InputMaybe<CaseStudyBodyCtaBannerFilter>;
  CaptionedImage?: InputMaybe<CaseStudyBodyCaptionedImageFilter>;
};

export type CaseStudyFilter = {
  title?: InputMaybe<StringFilter>;
  company?: InputMaybe<StringFilter>;
  coverImage?: InputMaybe<ImageFilter>;
  tags?: InputMaybe<StringFilter>;
  publishedDate?: InputMaybe<DatetimeFilter>;
  seo?: InputMaybe<CaseStudySeoFilter>;
  body?: InputMaybe<CaseStudyBodyFilter>;
};

export type CaseStudyConnectionEdges = {
  __typename?: 'CaseStudyConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<CaseStudy>;
};

export type CaseStudyConnection = Connection & {
  __typename?: 'CaseStudyConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<CaseStudyConnectionEdges>>>;
};

export type BlogPostSeo = {
  __typename?: 'BlogPostSeo';
  metaTitle?: Maybe<Scalars['String']['output']>;
  metaDescription?: Maybe<Scalars['String']['output']>;
  ogImage?: Maybe<Scalars['String']['output']>;
};

export type BlogPost = Node & Document & {
  __typename?: 'BlogPost';
  title: Scalars['String']['output'];
  excerpt?: Maybe<Scalars['String']['output']>;
  coverImage?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  publishedDate?: Maybe<Scalars['String']['output']>;
  seo?: Maybe<BlogPostSeo>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BlogPostSeoFilter = {
  metaTitle?: InputMaybe<StringFilter>;
  metaDescription?: InputMaybe<StringFilter>;
  ogImage?: InputMaybe<ImageFilter>;
};

export type BlogPostBodyCalloutFilter = {
  type?: InputMaybe<StringFilter>;
  heading?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
};

export type BlogPostBodyCtaBannerFilter = {
  heading?: InputMaybe<StringFilter>;
  buttonText?: InputMaybe<StringFilter>;
  buttonUrl?: InputMaybe<StringFilter>;
};

export type BlogPostBodyCaptionedImageFilter = {
  image?: InputMaybe<ImageFilter>;
  caption?: InputMaybe<StringFilter>;
  attribution?: InputMaybe<StringFilter>;
};

export type BlogPostBodyFilter = {
  Callout?: InputMaybe<BlogPostBodyCalloutFilter>;
  CTABanner?: InputMaybe<BlogPostBodyCtaBannerFilter>;
  CaptionedImage?: InputMaybe<BlogPostBodyCaptionedImageFilter>;
};

export type BlogPostFilter = {
  title?: InputMaybe<StringFilter>;
  excerpt?: InputMaybe<StringFilter>;
  coverImage?: InputMaybe<ImageFilter>;
  tags?: InputMaybe<StringFilter>;
  publishedDate?: InputMaybe<DatetimeFilter>;
  seo?: InputMaybe<BlogPostSeoFilter>;
  body?: InputMaybe<BlogPostBodyFilter>;
};

export type BlogPostConnectionEdges = {
  __typename?: 'BlogPostConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<BlogPost>;
};

export type BlogPostConnection = Connection & {
  __typename?: 'BlogPostConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BlogPostConnectionEdges>>>;
};

export type TestimonialsItems = {
  __typename?: 'TestimonialsItems';
  quote: Scalars['String']['output'];
  authorName: Scalars['String']['output'];
  authorRole?: Maybe<Scalars['String']['output']>;
  authorAvatar?: Maybe<Scalars['String']['output']>;
};

export type Testimonials = Node & Document & {
  __typename?: 'Testimonials';
  items?: Maybe<Array<Maybe<TestimonialsItems>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type TestimonialsItemsFilter = {
  quote?: InputMaybe<StringFilter>;
  authorName?: InputMaybe<StringFilter>;
  authorRole?: InputMaybe<StringFilter>;
  authorAvatar?: InputMaybe<ImageFilter>;
};

export type TestimonialsFilter = {
  items?: InputMaybe<TestimonialsItemsFilter>;
};

export type TestimonialsConnectionEdges = {
  __typename?: 'TestimonialsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Testimonials>;
};

export type TestimonialsConnection = Connection & {
  __typename?: 'TestimonialsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TestimonialsConnectionEdges>>>;
};

export type SiteSettingsSocialLinks = {
  __typename?: 'SiteSettingsSocialLinks';
  platform?: Maybe<Scalars['String']['output']>;
  url?: Maybe<Scalars['String']['output']>;
};

export type SiteSettings = Node & Document & {
  __typename?: 'SiteSettings';
  logoText?: Maybe<Scalars['String']['output']>;
  resumeFile?: Maybe<Scalars['String']['output']>;
  footerCopyright?: Maybe<Scalars['String']['output']>;
  footerLocation?: Maybe<Scalars['String']['output']>;
  contactEmail?: Maybe<Scalars['String']['output']>;
  socialLinks?: Maybe<Array<Maybe<SiteSettingsSocialLinks>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SiteSettingsSocialLinksFilter = {
  platform?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type SiteSettingsFilter = {
  logoText?: InputMaybe<StringFilter>;
  resumeFile?: InputMaybe<ImageFilter>;
  footerCopyright?: InputMaybe<StringFilter>;
  footerLocation?: InputMaybe<StringFilter>;
  contactEmail?: InputMaybe<StringFilter>;
  socialLinks?: InputMaybe<SiteSettingsSocialLinksFilter>;
};

export type SiteSettingsConnectionEdges = {
  __typename?: 'SiteSettingsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<SiteSettings>;
};

export type SiteSettingsConnection = Connection & {
  __typename?: 'SiteSettingsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SiteSettingsConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateHomepage: Homepage;
  createHomepage: Homepage;
  updateCapabilities: Capabilities;
  createCapabilities: Capabilities;
  updateCaseStudy: CaseStudy;
  createCaseStudy: CaseStudy;
  updateBlogPost: BlogPost;
  createBlogPost: BlogPost;
  updateTestimonials: Testimonials;
  createTestimonials: Testimonials;
  updateSiteSettings: SiteSettings;
  createSiteSettings: SiteSettings;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateHomepageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomepageMutation;
};


export type MutationCreateHomepageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomepageMutation;
};


export type MutationUpdateCapabilitiesArgs = {
  relativePath: Scalars['String']['input'];
  params: CapabilitiesMutation;
};


export type MutationCreateCapabilitiesArgs = {
  relativePath: Scalars['String']['input'];
  params: CapabilitiesMutation;
};


export type MutationUpdateCaseStudyArgs = {
  relativePath: Scalars['String']['input'];
  params: CaseStudyMutation;
};


export type MutationCreateCaseStudyArgs = {
  relativePath: Scalars['String']['input'];
  params: CaseStudyMutation;
};


export type MutationUpdateBlogPostArgs = {
  relativePath: Scalars['String']['input'];
  params: BlogPostMutation;
};


export type MutationCreateBlogPostArgs = {
  relativePath: Scalars['String']['input'];
  params: BlogPostMutation;
};


export type MutationUpdateTestimonialsArgs = {
  relativePath: Scalars['String']['input'];
  params: TestimonialsMutation;
};


export type MutationCreateTestimonialsArgs = {
  relativePath: Scalars['String']['input'];
  params: TestimonialsMutation;
};


export type MutationUpdateSiteSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteSettingsMutation;
};


export type MutationCreateSiteSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteSettingsMutation;
};

export type DocumentUpdateMutation = {
  homepage?: InputMaybe<HomepageMutation>;
  capabilities?: InputMaybe<CapabilitiesMutation>;
  caseStudy?: InputMaybe<CaseStudyMutation>;
  blogPost?: InputMaybe<BlogPostMutation>;
  testimonials?: InputMaybe<TestimonialsMutation>;
  siteSettings?: InputMaybe<SiteSettingsMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  homepage?: InputMaybe<HomepageMutation>;
  capabilities?: InputMaybe<CapabilitiesMutation>;
  caseStudy?: InputMaybe<CaseStudyMutation>;
  blogPost?: InputMaybe<BlogPostMutation>;
  testimonials?: InputMaybe<TestimonialsMutation>;
  siteSettings?: InputMaybe<SiteSettingsMutation>;
};

export type HomepageCompaniesMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  logo?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageSeoMutation = {
  metaTitle?: InputMaybe<Scalars['String']['input']>;
  metaDescription?: InputMaybe<Scalars['String']['input']>;
  ogImage?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageMutation = {
  headline?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  photo?: InputMaybe<Scalars['String']['input']>;
  shippedResultsLabel?: InputMaybe<Scalars['String']['input']>;
  companies?: InputMaybe<Array<InputMaybe<HomepageCompaniesMutation>>>;
  aboutHeading?: InputMaybe<Scalars['String']['input']>;
  aboutText?: InputMaybe<Scalars['String']['input']>;
  seo?: InputMaybe<HomepageSeoMutation>;
};

export type CapabilitiesTabsMetricsMutation = {
  highlight?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  detail?: InputMaybe<Scalars['String']['input']>;
  image1?: InputMaybe<Scalars['String']['input']>;
  image2?: InputMaybe<Scalars['String']['input']>;
  image3?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
  ctaText?: InputMaybe<Scalars['String']['input']>;
  ctaUrl?: InputMaybe<Scalars['String']['input']>;
};

export type CapabilitiesTabsMutation = {
  id?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
  accent?: InputMaybe<Scalars['String']['input']>;
  metrics?: InputMaybe<Array<InputMaybe<CapabilitiesTabsMetricsMutation>>>;
};

export type CapabilitiesMutation = {
  tabs?: InputMaybe<Array<InputMaybe<CapabilitiesTabsMutation>>>;
};

export type CaseStudySeoMutation = {
  metaTitle?: InputMaybe<Scalars['String']['input']>;
  metaDescription?: InputMaybe<Scalars['String']['input']>;
  ogImage?: InputMaybe<Scalars['String']['input']>;
};

export type CaseStudyMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  company?: InputMaybe<Scalars['String']['input']>;
  coverImage?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  publishedDate?: InputMaybe<Scalars['String']['input']>;
  seo?: InputMaybe<CaseStudySeoMutation>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type BlogPostSeoMutation = {
  metaTitle?: InputMaybe<Scalars['String']['input']>;
  metaDescription?: InputMaybe<Scalars['String']['input']>;
  ogImage?: InputMaybe<Scalars['String']['input']>;
};

export type BlogPostMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  excerpt?: InputMaybe<Scalars['String']['input']>;
  coverImage?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  publishedDate?: InputMaybe<Scalars['String']['input']>;
  seo?: InputMaybe<BlogPostSeoMutation>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type TestimonialsItemsMutation = {
  quote?: InputMaybe<Scalars['String']['input']>;
  authorName?: InputMaybe<Scalars['String']['input']>;
  authorRole?: InputMaybe<Scalars['String']['input']>;
  authorAvatar?: InputMaybe<Scalars['String']['input']>;
};

export type TestimonialsMutation = {
  items?: InputMaybe<Array<InputMaybe<TestimonialsItemsMutation>>>;
};

export type SiteSettingsSocialLinksMutation = {
  platform?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type SiteSettingsMutation = {
  logoText?: InputMaybe<Scalars['String']['input']>;
  resumeFile?: InputMaybe<Scalars['String']['input']>;
  footerCopyright?: InputMaybe<Scalars['String']['input']>;
  footerLocation?: InputMaybe<Scalars['String']['input']>;
  contactEmail?: InputMaybe<Scalars['String']['input']>;
  socialLinks?: InputMaybe<Array<InputMaybe<SiteSettingsSocialLinksMutation>>>;
};

export type HomepagePartsFragment = { __typename: 'Homepage', headline: string, subtitle: string, photo?: string | null, shippedResultsLabel?: string | null, aboutHeading?: string | null, aboutText?: string | null, companies?: Array<{ __typename: 'HomepageCompanies', name: string, logo?: string | null } | null> | null, seo?: { __typename: 'HomepageSeo', metaTitle?: string | null, metaDescription?: string | null, ogImage?: string | null } | null };

export type CapabilitiesPartsFragment = { __typename: 'Capabilities', tabs?: Array<{ __typename: 'CapabilitiesTabs', id: string, label: string, accent: string, metrics?: Array<{ __typename: 'CapabilitiesTabsMetrics', highlight: string, description: string, detail?: string | null, image1?: string | null, image2?: string | null, image3?: string | null, url?: string | null, ctaText?: string | null, ctaUrl?: string | null } | null> | null } | null> | null };

export type CaseStudyPartsFragment = { __typename: 'CaseStudy', title: string, company?: string | null, coverImage?: string | null, tags?: Array<string | null> | null, publishedDate?: string | null, body?: any | null, seo?: { __typename: 'CaseStudySeo', metaTitle?: string | null, metaDescription?: string | null, ogImage?: string | null } | null };

export type BlogPostPartsFragment = { __typename: 'BlogPost', title: string, excerpt?: string | null, coverImage?: string | null, tags?: Array<string | null> | null, publishedDate?: string | null, body?: any | null, seo?: { __typename: 'BlogPostSeo', metaTitle?: string | null, metaDescription?: string | null, ogImage?: string | null } | null };

export type TestimonialsPartsFragment = { __typename: 'Testimonials', items?: Array<{ __typename: 'TestimonialsItems', quote: string, authorName: string, authorRole?: string | null, authorAvatar?: string | null } | null> | null };

export type SiteSettingsPartsFragment = { __typename: 'SiteSettings', logoText?: string | null, resumeFile?: string | null, footerCopyright?: string | null, footerLocation?: string | null, contactEmail?: string | null, socialLinks?: Array<{ __typename: 'SiteSettingsSocialLinks', platform?: string | null, url?: string | null } | null> | null };

export type HomepageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomepageQuery = { __typename?: 'Query', homepage: { __typename: 'Homepage', id: string, headline: string, subtitle: string, photo?: string | null, shippedResultsLabel?: string | null, aboutHeading?: string | null, aboutText?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, companies?: Array<{ __typename: 'HomepageCompanies', name: string, logo?: string | null } | null> | null, seo?: { __typename: 'HomepageSeo', metaTitle?: string | null, metaDescription?: string | null, ogImage?: string | null } | null } };

export type HomepageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomepageFilter>;
}>;


export type HomepageConnectionQuery = { __typename?: 'Query', homepageConnection: { __typename?: 'HomepageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomepageConnectionEdges', cursor: string, node?: { __typename: 'Homepage', id: string, headline: string, subtitle: string, photo?: string | null, shippedResultsLabel?: string | null, aboutHeading?: string | null, aboutText?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, companies?: Array<{ __typename: 'HomepageCompanies', name: string, logo?: string | null } | null> | null, seo?: { __typename: 'HomepageSeo', metaTitle?: string | null, metaDescription?: string | null, ogImage?: string | null } | null } | null } | null> | null } };

export type CapabilitiesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type CapabilitiesQuery = { __typename?: 'Query', capabilities: { __typename: 'Capabilities', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, tabs?: Array<{ __typename: 'CapabilitiesTabs', id: string, label: string, accent: string, metrics?: Array<{ __typename: 'CapabilitiesTabsMetrics', highlight: string, description: string, detail?: string | null, image1?: string | null, image2?: string | null, image3?: string | null, url?: string | null, ctaText?: string | null, ctaUrl?: string | null } | null> | null } | null> | null } };

export type CapabilitiesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CapabilitiesFilter>;
}>;


export type CapabilitiesConnectionQuery = { __typename?: 'Query', capabilitiesConnection: { __typename?: 'CapabilitiesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'CapabilitiesConnectionEdges', cursor: string, node?: { __typename: 'Capabilities', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, tabs?: Array<{ __typename: 'CapabilitiesTabs', id: string, label: string, accent: string, metrics?: Array<{ __typename: 'CapabilitiesTabsMetrics', highlight: string, description: string, detail?: string | null, image1?: string | null, image2?: string | null, image3?: string | null, url?: string | null, ctaText?: string | null, ctaUrl?: string | null } | null> | null } | null> | null } | null } | null> | null } };

export type CaseStudyQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type CaseStudyQuery = { __typename?: 'Query', caseStudy: { __typename: 'CaseStudy', id: string, title: string, company?: string | null, coverImage?: string | null, tags?: Array<string | null> | null, publishedDate?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, seo?: { __typename: 'CaseStudySeo', metaTitle?: string | null, metaDescription?: string | null, ogImage?: string | null } | null } };

export type CaseStudyConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CaseStudyFilter>;
}>;


export type CaseStudyConnectionQuery = { __typename?: 'Query', caseStudyConnection: { __typename?: 'CaseStudyConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'CaseStudyConnectionEdges', cursor: string, node?: { __typename: 'CaseStudy', id: string, title: string, company?: string | null, coverImage?: string | null, tags?: Array<string | null> | null, publishedDate?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, seo?: { __typename: 'CaseStudySeo', metaTitle?: string | null, metaDescription?: string | null, ogImage?: string | null } | null } | null } | null> | null } };

export type BlogPostQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type BlogPostQuery = { __typename?: 'Query', blogPost: { __typename: 'BlogPost', id: string, title: string, excerpt?: string | null, coverImage?: string | null, tags?: Array<string | null> | null, publishedDate?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, seo?: { __typename: 'BlogPostSeo', metaTitle?: string | null, metaDescription?: string | null, ogImage?: string | null } | null } };

export type BlogPostConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BlogPostFilter>;
}>;


export type BlogPostConnectionQuery = { __typename?: 'Query', blogPostConnection: { __typename?: 'BlogPostConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'BlogPostConnectionEdges', cursor: string, node?: { __typename: 'BlogPost', id: string, title: string, excerpt?: string | null, coverImage?: string | null, tags?: Array<string | null> | null, publishedDate?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, seo?: { __typename: 'BlogPostSeo', metaTitle?: string | null, metaDescription?: string | null, ogImage?: string | null } | null } | null } | null> | null } };

export type TestimonialsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TestimonialsQuery = { __typename?: 'Query', testimonials: { __typename: 'Testimonials', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'TestimonialsItems', quote: string, authorName: string, authorRole?: string | null, authorAvatar?: string | null } | null> | null } };

export type TestimonialsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TestimonialsFilter>;
}>;


export type TestimonialsConnectionQuery = { __typename?: 'Query', testimonialsConnection: { __typename?: 'TestimonialsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TestimonialsConnectionEdges', cursor: string, node?: { __typename: 'Testimonials', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'TestimonialsItems', quote: string, authorName: string, authorRole?: string | null, authorAvatar?: string | null } | null> | null } | null } | null> | null } };

export type SiteSettingsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SiteSettingsQuery = { __typename?: 'Query', siteSettings: { __typename: 'SiteSettings', id: string, logoText?: string | null, resumeFile?: string | null, footerCopyright?: string | null, footerLocation?: string | null, contactEmail?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, socialLinks?: Array<{ __typename: 'SiteSettingsSocialLinks', platform?: string | null, url?: string | null } | null> | null } };

export type SiteSettingsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteSettingsFilter>;
}>;


export type SiteSettingsConnectionQuery = { __typename?: 'Query', siteSettingsConnection: { __typename?: 'SiteSettingsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SiteSettingsConnectionEdges', cursor: string, node?: { __typename: 'SiteSettings', id: string, logoText?: string | null, resumeFile?: string | null, footerCopyright?: string | null, footerLocation?: string | null, contactEmail?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, socialLinks?: Array<{ __typename: 'SiteSettingsSocialLinks', platform?: string | null, url?: string | null } | null> | null } | null } | null> | null } };

export const HomepagePartsFragmentDoc = gql`
    fragment HomepageParts on Homepage {
  __typename
  headline
  subtitle
  photo
  shippedResultsLabel
  companies {
    __typename
    name
    logo
  }
  aboutHeading
  aboutText
  seo {
    __typename
    metaTitle
    metaDescription
    ogImage
  }
}
    `;
export const CapabilitiesPartsFragmentDoc = gql`
    fragment CapabilitiesParts on Capabilities {
  __typename
  tabs {
    __typename
    id
    label
    accent
    metrics {
      __typename
      highlight
      description
      detail
      image1
      image2
      image3
      url
      ctaText
      ctaUrl
    }
  }
}
    `;
export const CaseStudyPartsFragmentDoc = gql`
    fragment CaseStudyParts on CaseStudy {
  __typename
  title
  company
  coverImage
  tags
  publishedDate
  seo {
    __typename
    metaTitle
    metaDescription
    ogImage
  }
  body
}
    `;
export const BlogPostPartsFragmentDoc = gql`
    fragment BlogPostParts on BlogPost {
  __typename
  title
  excerpt
  coverImage
  tags
  publishedDate
  seo {
    __typename
    metaTitle
    metaDescription
    ogImage
  }
  body
}
    `;
export const TestimonialsPartsFragmentDoc = gql`
    fragment TestimonialsParts on Testimonials {
  __typename
  items {
    __typename
    quote
    authorName
    authorRole
    authorAvatar
  }
}
    `;
export const SiteSettingsPartsFragmentDoc = gql`
    fragment SiteSettingsParts on SiteSettings {
  __typename
  logoText
  resumeFile
  footerCopyright
  footerLocation
  contactEmail
  socialLinks {
    __typename
    platform
    url
  }
}
    `;
export const HomepageDocument = gql`
    query homepage($relativePath: String!) {
  homepage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomepageParts
  }
}
    ${HomepagePartsFragmentDoc}`;
export const HomepageConnectionDocument = gql`
    query homepageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomepageFilter) {
  homepageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomepageParts
      }
    }
  }
}
    ${HomepagePartsFragmentDoc}`;
export const CapabilitiesDocument = gql`
    query capabilities($relativePath: String!) {
  capabilities(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...CapabilitiesParts
  }
}
    ${CapabilitiesPartsFragmentDoc}`;
export const CapabilitiesConnectionDocument = gql`
    query capabilitiesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: CapabilitiesFilter) {
  capabilitiesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...CapabilitiesParts
      }
    }
  }
}
    ${CapabilitiesPartsFragmentDoc}`;
export const CaseStudyDocument = gql`
    query caseStudy($relativePath: String!) {
  caseStudy(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...CaseStudyParts
  }
}
    ${CaseStudyPartsFragmentDoc}`;
export const CaseStudyConnectionDocument = gql`
    query caseStudyConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: CaseStudyFilter) {
  caseStudyConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...CaseStudyParts
      }
    }
  }
}
    ${CaseStudyPartsFragmentDoc}`;
export const BlogPostDocument = gql`
    query blogPost($relativePath: String!) {
  blogPost(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BlogPostParts
  }
}
    ${BlogPostPartsFragmentDoc}`;
export const BlogPostConnectionDocument = gql`
    query blogPostConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BlogPostFilter) {
  blogPostConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BlogPostParts
      }
    }
  }
}
    ${BlogPostPartsFragmentDoc}`;
export const TestimonialsDocument = gql`
    query testimonials($relativePath: String!) {
  testimonials(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TestimonialsParts
  }
}
    ${TestimonialsPartsFragmentDoc}`;
export const TestimonialsConnectionDocument = gql`
    query testimonialsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TestimonialsFilter) {
  testimonialsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TestimonialsParts
      }
    }
  }
}
    ${TestimonialsPartsFragmentDoc}`;
export const SiteSettingsDocument = gql`
    query siteSettings($relativePath: String!) {
  siteSettings(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SiteSettingsParts
  }
}
    ${SiteSettingsPartsFragmentDoc}`;
export const SiteSettingsConnectionDocument = gql`
    query siteSettingsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SiteSettingsFilter) {
  siteSettingsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SiteSettingsParts
      }
    }
  }
}
    ${SiteSettingsPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      homepage(variables: HomepageQueryVariables, options?: C): Promise<{data: HomepageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageQueryVariables, query: string}> {
        return requester<{data: HomepageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageQueryVariables, query: string}, HomepageQueryVariables>(HomepageDocument, variables, options);
      },
    homepageConnection(variables?: HomepageConnectionQueryVariables, options?: C): Promise<{data: HomepageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageConnectionQueryVariables, query: string}> {
        return requester<{data: HomepageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageConnectionQueryVariables, query: string}, HomepageConnectionQueryVariables>(HomepageConnectionDocument, variables, options);
      },
    capabilities(variables: CapabilitiesQueryVariables, options?: C): Promise<{data: CapabilitiesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CapabilitiesQueryVariables, query: string}> {
        return requester<{data: CapabilitiesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CapabilitiesQueryVariables, query: string}, CapabilitiesQueryVariables>(CapabilitiesDocument, variables, options);
      },
    capabilitiesConnection(variables?: CapabilitiesConnectionQueryVariables, options?: C): Promise<{data: CapabilitiesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CapabilitiesConnectionQueryVariables, query: string}> {
        return requester<{data: CapabilitiesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CapabilitiesConnectionQueryVariables, query: string}, CapabilitiesConnectionQueryVariables>(CapabilitiesConnectionDocument, variables, options);
      },
    caseStudy(variables: CaseStudyQueryVariables, options?: C): Promise<{data: CaseStudyQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CaseStudyQueryVariables, query: string}> {
        return requester<{data: CaseStudyQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CaseStudyQueryVariables, query: string}, CaseStudyQueryVariables>(CaseStudyDocument, variables, options);
      },
    caseStudyConnection(variables?: CaseStudyConnectionQueryVariables, options?: C): Promise<{data: CaseStudyConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CaseStudyConnectionQueryVariables, query: string}> {
        return requester<{data: CaseStudyConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CaseStudyConnectionQueryVariables, query: string}, CaseStudyConnectionQueryVariables>(CaseStudyConnectionDocument, variables, options);
      },
    blogPost(variables: BlogPostQueryVariables, options?: C): Promise<{data: BlogPostQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogPostQueryVariables, query: string}> {
        return requester<{data: BlogPostQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogPostQueryVariables, query: string}, BlogPostQueryVariables>(BlogPostDocument, variables, options);
      },
    blogPostConnection(variables?: BlogPostConnectionQueryVariables, options?: C): Promise<{data: BlogPostConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogPostConnectionQueryVariables, query: string}> {
        return requester<{data: BlogPostConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogPostConnectionQueryVariables, query: string}, BlogPostConnectionQueryVariables>(BlogPostConnectionDocument, variables, options);
      },
    testimonials(variables: TestimonialsQueryVariables, options?: C): Promise<{data: TestimonialsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialsQueryVariables, query: string}> {
        return requester<{data: TestimonialsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialsQueryVariables, query: string}, TestimonialsQueryVariables>(TestimonialsDocument, variables, options);
      },
    testimonialsConnection(variables?: TestimonialsConnectionQueryVariables, options?: C): Promise<{data: TestimonialsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialsConnectionQueryVariables, query: string}> {
        return requester<{data: TestimonialsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialsConnectionQueryVariables, query: string}, TestimonialsConnectionQueryVariables>(TestimonialsConnectionDocument, variables, options);
      },
    siteSettings(variables: SiteSettingsQueryVariables, options?: C): Promise<{data: SiteSettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteSettingsQueryVariables, query: string}> {
        return requester<{data: SiteSettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteSettingsQueryVariables, query: string}, SiteSettingsQueryVariables>(SiteSettingsDocument, variables, options);
      },
    siteSettingsConnection(variables?: SiteSettingsConnectionQueryVariables, options?: C): Promise<{data: SiteSettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteSettingsConnectionQueryVariables, query: string}> {
        return requester<{data: SiteSettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteSettingsConnectionQueryVariables, query: string}, SiteSettingsConnectionQueryVariables>(SiteSettingsConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  